server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shierhotel?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 8.134.37.7
    port: 5672
    username: shier
    password: 123456
    virtual-host: /
logging:
  level:
    cn.shier: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.shier.hotel.pojo